server:
  address: ":9999"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库连接配置
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default: # todo  修改成自己的密码
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/goframeshop"
    debug: true

# redis链接配置
redis:
  default:
    address: 127.0.0.1:6379
    db: 1
    pass:
    idleTimeout: 600

upload:
  path: "upload"