// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gongzhaoweishop/internal/logic/admin"
	_ "gongzhaoweishop/internal/logic/article"
	_ "gongzhaoweishop/internal/logic/bizctx"
	_ "gongzhaoweishop/internal/logic/file"
	_ "gongzhaoweishop/internal/logic/middleware"
	_ "gongzhaoweishop/internal/logic/order"
	_ "gongzhaoweishop/internal/logic/permission"
	_ "gongzhaoweishop/internal/logic/position"
	_ "gongzhaoweishop/internal/logic/role"
	_ "gongzhaoweishop/internal/logic/rotation"
	_ "gongzhaoweishop/internal/logic/session"
)
