gfcli:
  # 工具编译配置
  build:
    name: "goframe-shop-v2"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0

  # dao生成
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/goframeshop"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true